### PR TITLE
Made regen happen automatically instead of on player sector join.

### PR DESCRIPTION
**Pull request by Pasukaru**
The regen rate is configurable.

### CODE REVIEW

**Comment by dirtyredz** [comment]
Very nice addition!

**Comment by Pasukaru** [comment]
I played around with this script a bit more.
In my version, i use a regen time of 3600 = 1h. 10 Minutes seemed pretty OP as default value.

Also, adding a 
`function RegenerativeAsteroids.getUpdateInterval() return 1 end`
(or similar, don't remember the exact name)
makes the script not execute every frame, but rather every second - minor performance improvement since the timer does not need to be checked every frame.

If you want, I can push these changes later (I'm not at home at the moment and don't have them here)

**Comment by dirtyredz** [comment]
I wouldent mind taking a look at those changes.

Im finally getting some time to myself this past few days and after ive finished with my website redesign ill be making some changes to avorion stuff.

**Comment by Pasukaru** [comment]
As promised, the changes are now pushed. :)

**Pull request closed without merging**
